site_name: "Projet Millesima S6"
site_url: "https://github.guezoloic.com/millesima-ai-engine/"

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings

extra:
  generator: false

copyright: "Loïc GUEZO & Chahrazad DAHMANI – UPEC S6 – 2026"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
